jobs:
  - job: AspNetCore
    pool:
      name: Default
      demands:
        - msbuild
        - visualstudio
        - vstest
    steps:
      - task: NuGetToolInstaller@0
        displayName: "Use NuGet"
        inputs:
          versionSpec: 4.4.1

      - task: NuGetCommand@2
        displayName: "NuGet restore"
        inputs:
          restoreSolution: "$(Parameters.solution)"

      - task: MSBuild@1
        inputs:
          solution: '**/*.sln'
          msbuildArchitecture: 'x64'
          platform: "$(BuildPlatform)"
          configuration: "$(BuildConfiguration)"

      - task: VSTest@2
        displayName: "Test"
        inputs:
          testAssemblyVer2: |
            **\*test*.dll
            !**\obj\**
            platform: '$(BuildPlatform)'
            configuration: '$(BuildConfiguration)'

      - task: whitesource.whiteSource-bolt-v2.bolt.wss.WhiteSource@21
        displayName: WhiteSource
        inputs:
          projectName: "$(SourceBranchName)"

      - task: ArchiveFiles@2
        displayName: 'Archive FastCarzWebApp'
        inputs:
          rootFolderOrFile: $(System.DefaultWorkingDirectory)\Q1\app\DevOpsTest\FastCarzWebApp\bin\$(BuildConfiguration)\netcoreapp3.1
          includeRootFolder: false
          archiveFile: '$(Build.ArtifactStagingDirectory)/FastCarzWebApp.zip'

      - task: ArchiveFiles@2
        displayName: 'Archive FastCarzWebApi'
        inputs:
          rootFolderOrFile: $(System.DefaultWorkingDirectory)\Q1\app\DevOpsTest\FastCarzWebApi\bin\$(BuildConfiguration)\netcoreapp3.1
          includeRootFolder: false
          archiveFile: '$(Build.ArtifactStagingDirectory)/FastCarzWebApi.zip'

      - task: PublishBuildArtifacts@1
        displayName: "Publish"
        inputs:
          PathtoPublish: "$(build.artifactstagingdirectory)"
          ArtifactName: "$(Parameters.ArtifactName)"
        condition: succeededOrFailed()
