parameters:
  azuresubscription: ""
  staterg: ""
  statesa: ""
  statecaontainer: ""
  backendazuremKey: ""
  configdir: ""

jobs:
  - job: Terraform
    pool:
      name: Default
      demands:
        agent.os -equals Linux

    steps:
      - task: TerraformTaskV2@2
        displayName: Init
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: '${{ parameters.azuresubscription }}'
          backendAzureRmResourceGroupName: ${{ parameters.staterg }}
          backendAzureRmStorageAccountName: ${{ parameters.statesa }}
          backendAzureRmContainerName: ${{ parameters.statecaontainer }}
          backendAzureRmKey: ${{ parameters.backendazuremKey }}
          workingDirectory: ${{ parameters.configdir }}
      
      - task: TerraformTaskV2@2
        displayName: Apply
        inputs:
          provider: 'azurerm'
          command: 'apply'
          backendServiceArm: '${{ parameters.azuresubscription }}'
          backendAzureRmResourceGroupName: ${{ parameters.staterg }}
          backendAzureRmStorageAccountName: ${{ parameters.statesa }}
          backendAzureRmContainerName: ${{ parameters.statecaontainer }}
          backendAzureRmKey: ${{ parameters.backendazuremKey }}
          workingDirectory: ${{ parameters.configdir }}