parameters:
  azuresubscription: ""
  staterg: ""
  statesa: ""
  statecaontainer: ""
  backendazuremkey: ""
  configdir: ""
  securitykv: ""

jobs:
  - job: Terraform
    pool:
      name: Default
      demands:
        agent.os -equals Linux
    steps:
      - task: AzureKeyVault@1
        inputs:
          azureSubscription: '${{ parameters.azuresubscription }}'
          keyVaultName: '${{ parameters.securitykv }}'
          secretsFilter: '*'
      - task: TerraformCLI@0
        displayName: Init
        inputs:
          backendType: 'azurerm'
          command: 'init'
          backendServiceArm: '${{ parameters.azuresubscription }}'
          backendAzureRmResourceGroupName: '${{ parameters.staterg }}'
          backendAzureRmStorageAccountName: '${{ parameters.statesa }}'
          backendAzureRmContainerName: '${{ parameters.statecaontainer }}'
          backendAzureRmKey: '${{ parameters.backendazuremkey }}'
          workingDirectory: '${{ parameters.configdir }}'
          allowTelemetryCollection: true
      - bash: |
          terrascan scan -d ${{ parameters.configdir }} -l fatal
        displayName: TerraScan
      # - bash: |
      #     tfsec ${{ parameters.configdir }}
      #   displayName: TfSec
      # - bash: |
      #     checkov --directory ${{ parameters.configdir }}
        # displayName: Checkov
      - task: TerraformCLI@0
        displayName: Validate
        inputs:
          backendType: 'azurerm'
          command: 'validate'
          backendServiceArm: '${{ parameters.azuresubscription }}'
          backendAzureRmResourceGroupName: '${{ parameters.staterg }}'
          backendAzureRmStorageAccountName: '${{ parameters.statesa }}'
          backendAzureRmContainerName: '${{ parameters.statecaontainer }}'
          backendAzureRmKey: '${{ parameters.backendazuremkey }}'
          workingDirectory: '${{ parameters.configdir }}'
          allowTelemetryCollection: true
        env:
          TF_IN_AUTOMATION: 'True'
          tenant_id: '$(tenant-id)'
          subscription_id: '$(subscription-id)'
          client_id: '$(client-id)'
          client_secret: '$(client-secret)'
      - task: TerraformCLI@0
        displayName: Plan
        inputs:
          backendType: 'azurerm'
          command: 'plan'
          backendServiceArm: '${{ parameters.azuresubscription }}'
          backendAzureRmResourceGroupName: '${{ parameters.staterg }}'
          backendAzureRmStorageAccountName: '${{ parameters.statesa }}'
          backendAzureRmContainerName: '${{ parameters.statecaontainer }}'
          backendAzureRmKey: '${{ parameters.backendazuremkey }}'
          workingDirectory: '${{ parameters.configdir }}'
          publishPlanResults : 'plan_results'
          allowTelemetryCollection: true
          runAzLogin: true