parameters:
  azuresubscription: ""
  staterg: ""
  statesa: ""
  statecaontainer: ""
  backendazuremKey: ""
  configdir: ""

jobs:
  - job: Terraform
    pool:
      name: Default
      demands:
        agent.os -equals Linux

    steps:
      - task: TerraformCLI@0
        displayName: Init
        inputs:
          backendType: 'azurerm'
          command: 'init'
          backendServiceArm: '${{ parameters.azuresubscription }}'
          backendAzureRmResourceGroupName: '${{ parameters.staterg }}'
          backendAzureRmStorageAccountName: '${{ parameters.statesa }}'
          backendAzureRmContainerName: '${{ parameters.statecaontainer }}'
          backendazuremKey: '${{ parameters.backendazuremKey }}'
          workingDirectory: '${{ parameters.configdir }}'
          allowTelemetryCollection: true
      
      - task: TerraformCLI@0
        displayName: Apply
        inputs:
          backendType: 'azurerm'
          command: 'apply'
          backendServiceArm: '${{ parameters.azuresubscription }}'
          backendAzureRmResourceGroupName: '${{ parameters.staterg }}'
          backendAzureRmStorageAccountName: '${{ parameters.statesa }}'
          backendAzureRmContainerName: '${{ parameters.statecaontainer }}'
          backendazuremKey: '${{ parameters.backendazuremKey }}'
          workingDirectory: '${{ parameters.configdir }}'
          allowTelemetryCollection: true