trigger:
  branches:
    include:
    - master
    - main

variables:
  Parameters.solution: $(System.DefaultWorkingDirectory)\Q1\app\DevOpsTest\DevOpsTest.sln
  BuildPlatform: Any CPU
  BuildConfiguration: Release
  Parameters.ArtifactName: drop

stages:
  - stage: build
    jobs:
      - template: templates\job-build.yml

  - stage: dev
    dependsOn: build
    jobs:
      - template: templates\job-deploy.yml
        parameters:
          env: dev
          azuresubscription: dev-sub
          webappname: devopstestwebapp-pi-dev
          webapiname: devopstestwebapi-pi-dev
          apps: ["devopstestwebapp-pi-dev","devopstestwebapi-pi-dev"]

  - stage: qa
    dependsOn: dev
    jobs:
      - template: templates\job-deploy.yml
        parameters:
          env: qa
          azuresubscription: qa-sub
          webappname: devopstestwebapp-pi-qa
          webapiname: devopstestwebapi-pi-qa
          apps: ["devopstestwebapp-pi-qa","devopstestwebapi-pi-qa"]

  - stage: prod
    dependsOn: qa
    jobs:
      - template: templates\job-deploy.yml
        parameters:
          env: prod
          azuresubscription: prod-sub
          webappname: devopstestwebapp-pi-prod
          webapiname: devopstestwebapi-pi-prod
          apps: ["devopstestwebapp-pi-prod","devopstestwebapi-pi-prod"]